.TH ctt_process_options 3 "\n[year]-\n[mo]-\n[dy]" "Linux"
.
.SH NAME
ctt_process_options - Interprets command line arguments according to an array of option instructions.
.
.SH SYNOPSIS
.PP
.B #include <ctt.h>
.PP
.BI 
.
.SH DESCRIPTION
.
.SH EXAMPLE
.
.SH SEE ALSO
.BR ctt "(3), " ctt_getdents "(3), " ctt_get_keypress "(3), "
.BR ctt_get_line "(3), " ctt_indexed_string "(3), "
.BR ctt_itoa_buff "(3), "  ctt_pick_from_list "(3), "
