.TH ctt_get_line 3 "\n[year]-\n[mo]-\n[dy]" "Linux"
.
.SH NAME
ctt_get_line - Buffered access to lines in a file
.
.SH SYNOPSIS
.PP
.B #include <ctt.h>
.PP
.BI 
.
.SH DESCRIPTION
.
.SH EXAMPLE
.
.SH SEE ALSO
.BR ctt "(3), " ctt_getdents "(3), " ctt_get_keypress "(3), "
.BR ctt_indexed_string "(3), "
.BR ctt_itoa_buff "(3), "  ctt_pick_from_list "(3), "
.BR ctt_process_options "(3)"
